### ISSUE TITLE
install the torch_sparse

### ISSUE THREAD

**Issue by LvShengZe903** [JinheonBaek/GMT#16]
when i run the code. The torch version used is 1.4.0 the conda version is 10.1 but when I use torch_sparse version 0.5.1 the conda version is 10.0 and the torch_sparse version 0.4.4 not has SparseTensor, I  want to know the right version of torch_sparse. I look forward to your early reply.
![image](https://user-images.githubusercontent.com/51954425/132793412-84f9b053-2b42-4697-b6a5-ec73e818b6fd.png)
![image](https://user-images.githubusercontent.com/51954425/132793475-9c4d8acc-b5c9-4978-bc3f-fa88916317d8.png)

**Comment by JinheonBaek** [comment]
Hi,

Thank you for your interest in our work.
The latest version of torch_sparse we tested is 0.6.9.

In addition to this, you can also use the torch version 1.7.x with CUDA version 11.0.

Best,
Jinheon Baek

**Comment by LvShengZe903** [comment]
> Hi,
> 
> Thank you for your interest in our work.
> The latest version of torch_sparse we tested is 0.6.9.
> 
> In addition to this, you can also use the torch version 1.7.x with CUDA version 11.0.
> 
> Best,
> Jinheon Baek

Thank you for your early reply. The relation of the version of torch_geometric、 torch_sparse、 torch_scatter and  torch_cluster is serious. Could you please show me your particular requirement.txt or dependencies? look forward your kind advide.

**Comment by JinheonBaek** [comment]
I forgot the exact version that I used for reporting results, however below are the latest versions that we have tested.

torch: 1.7.1
torch_geometric: 1.7.0
torch_sparse: 0.6.9
torch_scatter: 2.0.6
torch_cluster: 1.5.9

**Comment by LvShengZe903** [comment]
> I forgot the exact version that I used for reporting results, however below are the latest versions that we have tested.
> 
> torch: 1.7.1
> torch_geometric: 1.7.0
> torch_sparse: 0.6.9
> torch_scatter: 2.0.6
> torch_cluster: 1.5.9

Thank you for your reply. I have solved the version problem. But when graph classification on TUdatasts DD, exists an error.
![image](https://user-images.githubusercontent.com/51954425/132842437-9382fe3f-d5ff-4887-94cd-953b55d79968.png)

**Comment by JinheonBaek** [comment]
Thank you for pointing out the bug in our code.

While the code in the provided script does not make an error,
the error comes from the dimensional difference between the GMPool_G's output and the classifier's input when we use one single pooling layer (e.g., GMPool_G or GMPool_I, instead of GMPool_G-SelfAtt-GMPool_I).

After checking our code, we found that our code has not used the already defined last layer of the pooling function, which we fix now.

Thanks.

**Comment by LvShengZe903** [comment]
> Thank you for pointing out the bug in our code.
> 
> While the code in the provided script does not make an error,
> the error comes from the dimensional difference between the GMPool_G's output and the classifier's input when we use one single pooling layer (e.g., GMPool_G or GMPool_I, instead of GMPool_G-SelfAtt-GMPool_I).
> 
> After checking our code, we found that our code has not used the already defined last layer of the pooling function, which we fix now.
> 
> Thanks.

Thank you for your patience

**Comment by JinheonBaek** [comment]
If you have any further questions, feel free to ask me.
