### ISSUE TITLE
Problem about GMPool_I

### ISSUE THREAD

**Issue by dongZheX** [JinheonBaek/GMT#19]
Thanks for the codes and this is a interesting work.

I have a question about the implementation about GMPool_I.

In GMPool_I, the seed matrix S \in R^{1 \times k}, where the k is the number of nodes after GMPool_G.
But, In module GMPool_I,  whatever S is, the attentional matrix A is a all-1 Matrix \in R^{1 \times k}  because of the col-wise softmax
```
tensor([[[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]]], device='cuda:1',
       grad_fn=<SoftmaxBackward0>)
```

It seems that the output of GMPool_I  is equivalent to  sum(WH+b) with FFN and shortcut . It looks like more reasonable to use a row-wise softmax for GMPool_I.  Is there some wrong with my understanding ?

Looking forward your reply.

**Comment by JinheonBaek** [comment]
Hi,
thank you for your interest and great question!

This is not a bug, but rather our purpose. 
In specific, we indeed use the col-wise softmax to make the overall architecture as powerful as the WL test. Considering the example of Graph Isomorphism Network (GIN) that uses the summation over all node representations for approximating the WL test. You can check the details in Section 3.3, Section 3.4, and Proof in Appendix A of our paper.

You can also use the row-wise softmax without using the cluster option in Line #29 of layers.py, but we found that this row-wise GMT mostly underperforms our proposed col-wise GMT.

Finally, the above result only happens in the final layer, where we reduce all remaining nodes into one particular node with one seed vector, thus this is the same as the sum pooling. You are correct. However, please note that, when we reduce n nodes into k different nodes, the col-wise softmax correctly assigns k cluster values (summed to one) for each node; the matrix is not the all-1 matrix.

**Comment by dongZheX** [comment]
> Hi, thank you for your interest and great question!
> 
> This is not a bug, but rather our purpose. In specific, we indeed use the col-wise softmax to make the overall architecture as powerful as the WL test. Considering the example of Graph Isomorphism Network (GIN) that uses the summation over all node representations for approximating the WL test. You can check the details in Section 3.3, Section 3.4, and Proof in Appendix A of our paper.
> 
> You can also use the row-wise softmax without using the cluster option in Line #29 of layers.py, but we found that this row-wise GMT mostly underperforms our proposed col-wise GMT.
> 
> Finally, the above result only happens in the final layer, where we reduce all remaining nodes into one particular node with one seed vector, thus this is the same as the sum pooling. You are correct. However, please note that, when we reduce n nodes into k different nodes, the col-wise softmax correctly assigns k cluster values (summed to one) for each node; the matrix is not the all-1 matrix.


Get it. Thanks for your reply. While reducing n nodes into k different nodes, col-wise softmax is necessary (same as DiffPool). But, to my knowledge and experiments, in hiv datasets, a mean or sum global pooling doesn't perform better than GlobalAttentionPool which assign nodes different weights. Maybe the method to get node weights of the row-wise GMT doesn't good enough. I think GMPool_l+SelfAtt+ some better global pooling may be work. I'all try it.

Thanks again.
