### ISSUE TITLE
Is the reported performance based on 100 times of training?

### ISSUE THREAD

**Issue by yunchong-song** [JinheonBaek/GMT#20]
Hi! This is a fantastic work! However, can I ask if the reported performance is based on 100 times of training? In Section **C.2 GRAPH CLASSIFICATION**, you mentioned:

> We then report the average performances on the validation and test sets, by performing overall experiments 10 times with different seeds.

Does this means your reported performance is based on 10folds*10seeds, which means 100 trained models in total? Or 10folds with different seeds?

**Comment by JinheonBaek** [comment]
Hi, thank you for your interest!

Yes, the reported performance is based on 100 (10 x 10) times of training.
Exactly, 10 folds x 10 seeds, which results in 100 trained models.

To be more specific,
Seed 41: 1 fold, 2 fold, 3 fold, ..., 10 fold (10 models),
Seed 42: 1 fold, 2 fold, 3 fold, ..., 10 fold (10 models),
...
Seed 50: 1 fold, 2 fold, 3 fold, ..., 10 fold (10 models),
thus the total number is 100.

If you have any questions, feel free to let us know.

**Comment by yunchong-song** [comment]
> Hi, thank you for your interest!
> 
> Yes, the reported performance is based on 100 (10 x 10) times of training. Exactly, 10 folds x 10 seeds, which results in 100 trained models.
> 
> To be more specific, Seed 41: 1 fold, 2 fold, 3 fold, ..., 10 fold (10 models), Seed 42: 1 fold, 2 fold, 3 fold, ..., 10 fold (10 models), ... Seed 50: 1 fold, 2 fold, 3 fold, ..., 10 fold (10 models), thus the total number is 100.
> 
> If you have any questions, feel free to let us know.

Thank you for clarifying!

**Comment by soumyapal91** [comment]
Hi, are the 10 seeds 41-50 in all experiments?

**Comment by JinheonBaek** [comment]
I cannot remember the exact numbers of seeds that we used in our experiments, but it might be somewhere between 30-60. I think it was 38-47, but I am not sure.
